# MongoDB
spring.data.mongodb.uri=mongodb+srv://hulbertarango:Arango2004@micluster.82ghj.mongodb.net/shopSystem?retryWrites=true&w=majority&appName=miCluster
spring.data.mongodb.database=shopSystem
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Correo
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=supermercadossg@gmail.com
spring.mail.password=NestoR2909
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Documentación
springdoc.use-management-port=true

# Configuración del puerto
server.address=0.0.0.0
server.port=${PORT:8080}

# Spring Web
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# Cloudinary
cloudinary.cloud-name=dkojfl0iu
cloudinary.api-key=116688446473926
cloudinary.api-secret=Nk5joTyu4hFHPdwuZ-V948x5H5c

# Jackson
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

# Archivos
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Mercado Pago
mercadopago.access.token=APP_USR-6804257661611202-040220-21c5efb630df7224dc0e46b3e957cf3a-2368856858

# ? MONITOREO (Micrometer + Prometheus)
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.endpoints.web.base-path=/actuator
